# Generated by Django 4.0.4 on 2022-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_user_is_archived_user_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('UNRD', 'Unread Messages'), ('RD', 'Read Messages'), ('AC', 'Account created')], default='UNRD', max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
